{% set name = "jobtastic" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jobtastic-{{ version }}.tar.gz
  sha256: 25b98692183a9254ede363129bbe89d505b7396badd87a5c0a5ba338512aade1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=2.6
    - django
    - pip
  run:
    - python >=2.6
    - psutil
    - celery >=3.1,<5

test:
  imports:
    - jobtastic
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://policystat.github.com/jobtastic
  summary: Make your user-facing Celery jobs totally awesomer
  license: MIT
  license_file: LICENSE
  description: |
    Jobtastic makes your user-responsive long-running Celery jobs totally awesomer.
    Celery is the ubiquitous python job queueing tool and jobtastic is a python
    library that adds useful features to your Celery tasks. Specifically, these are
    features you probably want if the results of your jobs are expensive or if your
    users need to wait while they compute their results.
  dev_url: https://github.com/PolicyStat/jobtastic

extra:
  recipe-maintainers:
    - sodre
